spring:
  application:
    name: Config-Prod
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch_registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
